services:
  evermeet:
    image: f6527d3d0fcaed9ef411ed6999de9b6efcc2594f8995ab54918457696758af4f
    volumes:
      - ./config-docker.yaml:/home/node/app/config.yaml
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
  caddy:
    image: caddy:2
    restart: always
    ports:
      - 3005:3005
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro